[package]
name = "resonite_clipboard-rs"
version = "0.1.0"
edition = "2024"

[lib]
name = "resonite_clipboard_rs"
crate-type = ["dylib"]

[dependencies]
safer-ffi = "0.1.13"
wl-clipboard-rs = "0.9.2"
libc = "0.2.175"
